title: Matthew Jeffery
name: Matthew Jeffery
email: matthewjeffery07@gmail.com
description: Student • Web Developer

baseurl: "/blog"
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "Internet of Things"
project_one_description: "For Project 1 in the B.I.T course I joined the Internet of Things group. This project focuses on the inter-networking of devices such as smart devices, sensors, software, and other items embedded with electronics. The IoT uses slightly different technology than WiFI to achieve this goal. Our IoT solution is implemented using LoRaWAN. The idea is to research and develop an open LoRaWAN consisting of one or more gateway devices, multiple sensor devices, and a central server. All of this in the Dunedin area, to provide access to user data for use in custom mobile/web/desktop applications."

project_one_url: https://gitlab.op-bit.nz/BIT/Project/Internet-Of-Things/applications/tree/master/Web-ThirstyPlant
project_one_icon: location_on

project_two: BoysTrip
project_two_description: My first website built using the Silverstripe CMS. 
project_two_url: https://boys-trip.co.nz
project_two_icon: photo_camera


project_three: CT Business Solutions
project_three_description: Website I built while working at The Logic Studio
project_three_url: https://ctbs.nz
project_three_icon: hotel


project_four: Knox & Anderson
project_four_description: Website I built while working at The Logic Studio
project_four_url: http://knoxandanderson.co.nz
project_four_icon: restaurant

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

experience:
  - name: csharp
  - name: css3
  - name: d3js
  - name: django
  - name: bootstrap
  - name: html5
  - name: java
  - name: javascript
  - name: mongodb
  - name: mysql
  - name: nodejs
  - name: php
  - name: postgresql
  - name: python
  - name: react
  - name: sass
  - name: sequelize
  - name: python
  - name: webpack
  - name: wordpress

tools:
#  - name: amazonwebservices
  - name: android
#  - name: angularjs
 # - name: apache
 # - name: appcelerator
 # - name: apple
 # - name: atom
 # - name: babel
 # - name: backbonejs
 # - name: bitbucket
 # - name: bootstrap
 # - name: bower
 # - name: c
 # - name: chrome
 # - name: codeigniter
 # - name: coffescript
 # - name: confluence
 # - name: cplusplus
#  - name: csharp
#  - name: css3
#  - name: cucumber
#  - name: d3js
#  - name: debian
#  - name: devicon
#  - name: django
#  - name: docker
#  - name: doctrine
#  - name: dot-net
#  - name: drupal
#  - name: erlang
#  - name: facebook
#  - name: firefox
#  - name: foundation
#  - name: gatling
#  - name: gimp
  - name: git
  - name: github
  - name: gitlab
#  - name: go
#  - name: google
#  - name: gradle
#  - name: grunt
#  - name: gulp
#  - name: heroku
#  - name: html5
#  - name: ie10
#  - name: illustrator
#  - name: inkscape
#  - name: itellij
#  - name: java
#  - name: jasmine
#  - name: javascript
#  - name: laravel
#  - name: less
  - name: linux
#  - name: meteor
#  - name: mocha
#  - name: mongodb
#  - name: moodle
#  - name: mysql
#  - name: nginx
#  - name: nodejs
#  - name: nodewebkit
#  - name: oracle
#  - name: photoshop
#  - name: php
#  - name: phpstorm
#  - name: protractor
#  - name: postgresql
#  - name: python
   - name: pycharm
#  - name: rails
#  - name: react
#  - name: redhat
#  - name: redis
#  - name: ruby
#  - name: rubymine
#  - name: safari
#  - name: sass
#  - name: sequelize
   - name: slack
#  - name: sourcetree
#  - name: ssh
#  - name: swift
#  - name: symfony
#  - name: tomcat
#  - name: travis
#  - name: trello
#  - name: twitter
#  - name: typescript
   - name: ubuntu
#  - name: vim
#  - name: visualstudio
#  - name: vuejs
#  - name: webpack
#  - name: webstorm
#  - name: windows8
#  - name: wordpress
#  - name: yii
#  - name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

# project_button: Github

# github: https://github.com/jameshamann/jekyll-material-theme
# medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
# google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

# cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
